version: '3.9'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dbtestfullstack
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=blog_test
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - network-connect

networks:
  network-connect:
    name: blog_test-fk-join-network
